import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  main: {
    paddingTop: "10%",
    height: "100%",
    backgroundColor: "white",
    overflowX: "hidden",
  },
  buttons: {
    // border: "2px solid rgb(74, 4, 4)",
    borderWidth: 1,
    borderColor: "rgb(74, 4, 4)",
    height: 35,
    width: 35,
    borderRadius: 10,
    borderStyle: "solid",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
    transform: [{ rotate: "45deg" }],
    // position: "fixed",
    // backgroundColor:'red',
    zIndex: 3,
    left: 20,
  },
  title: {
    textAlign: "center",
    marginTop: -35,
    fontSize: 18,
    // backgroundColor:'red',
    // position: "fixed",
    width: "100%",
    // backgroundColor: "red",
    // height: 30,
    // backgroundColor: "red",
    // paddingTop: 25,
    zIndex: 2,
  },
  container: {
    borderRadius: 10,
    // border: "2px solid rgb(74, 4, 4) ",
    borderWidth: 1,
    borderColor: "rgb(74, 4, 4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  LButtons: {
    // border: "2px solid rgb(74, 4, 4)",

    borderWidth: 1,
    borderColor: "rgb(74, 4, 4)",
    width: "90%",
    borderRadius: 10,
    height: 45,
    paddingLeft: 10,
    marginTop: 15,
  },
  bText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  iText: {
    fontSize: 13,
  },
  paddedButton: {
    backgroundColor: "rgb(74, 4, 4)",
    marginTop: 20,
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    // borderRadius: 10,
    marginBottom: 30,
  },

  cartItem: {
    // border: "2px solid rgb(74, 4, 4)",

    borderWidth: 1,
    borderColor: "rgb(74, 4, 4)",
    // borderRadius: 20,
    marginBottom: 20,
    padding: 10,
    paddingLeft:20,
    paddingRight:20,
    borderRadius:10,
    overflow: "hidden",
  },
});
